<!DOCTYPE html>
<html>
<head>
  <title>Tela de login</title>
  <link rel="stylesheet" type="text/css" href="css/style.css">
  <link href="/img/favicon.ico" rel="icon" type="image/x-icon" />
</head>
<body>
  <div class="login-box">
    <h1>Login</h1>
    <form action="<?= $this->url('auth', ['action' => 'auth', 'ds_login' => 'ds_login', 'ds_login' => 'ds_senha']) ?>">
      <div class="textbox">
        <i class="fas fa-user"></i>
        <input type="text" placeholder="Usuário" name="ds_login" required>
      </div>
      <div class="textbox">
        <i class="fas fa-lock"></i>
        <input type="password" placeholder="Senha" name="ds_senha" required>
      </div>
      <input class="btn" type="submit" value="Entrar">
    </form>
  </div>
</body>
</html>
